### ISSUE TITLE
PLiCy版(2019) 取り込み

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#201]
# 進め方
`develop` から `feature/なんとか` ブランチを切る (このブランチをBとする)

ブランチB からさらにブランチを切って、ブランチ Bに向けてPRを作ってマージしていく

## ブランチBへの取り込み手順
1. ブランチ B からブランチを作成
2. git merge (取り込みたい PLiCy側のコミットハッシュ)
3. コンフリクトを解消する。必要に応じてコードを変更する。
4. ブランチ B 向けPRを作成する。

PLiCy側のコミットハッシュは #100 を参照

## Phase 1: QS複数化 v3.3.0 #175 

<details>
<summary>リリース済。クリックで開く。</summary>

ブランチB = `feature/plicy-2019`

- [x] f1d37cd : QS複数化の準備
- [x] 278aac6 : デバイス判定クラス (ただ、これは現行Wingに先行投入していたため、実質差分なし)　#180
- [x] dd99635 : QS複数化のスタイルを当てる #181 
- [x] 596a803 : useGameEnd の削除 関連する出し分けの処理は最新から持ってきた #183 
- [x] （最新 `develop` 取り込み) #184 
- [x] f998c00 : 戦闘時にゲームパッド振動 + メッセージウィンドウを閉じた後1F待機 #185 
- [x] d762480 : ゲームパッドの　`BUTTON_INDEX_Y` ボタン押下時にヘルプ表示, デバイスごとにヘルプのボタン内容切り替え #199 
- [x] 86165ee : `$gamepad_button` マクロ追加  ゲームパッドのボタンをボックス内のアイテム使用にアサイン **※アイテム番号アサインの初期化処理が間違っているので、後続コミットとセットで入れること**  #200 
- [x] c4eca74 : `GamePadState からスティックの傾斜系` を `GamePadStateAxes` に分離, `GamePadState` に スティックのIDを追加, 前コミットの不具合修正 #200 
- [x] baffea1 (cherry-pick): (Nintendo環境のみ) breakとするべき場所をreturnとしていた不具合を修正 #206 
- [x] 19deec9 385dd53 (chery-pick) : (ゲーム機などで、ヘルプを開かないための変数) _useHelp変数削除 #206 
- [x] b651572 の部分cherry-pick (本来Phase3): セーブ禁止時にQuickSave選択画面が表示される不具合を修正 #207
- [x]  96c2713 の部分chery-pick(本来Phase3): 中断からの再開時にメッセージウィンドウのnull参照を回避するための MessageWindow, ScoreWindow を newする位置を変更, faceのクリア位置変更 #208 
- [x] 43799b8 の部分cherry-pick (本来Phase3): requestAnimationFrame は window.のものを使う #209 

</details>

## Phase 2: パスワードセーブ関係以外 v3.4.1 #229 
注) v3.3.1 は hotfix に使われました #237

<details>
<summary>リリース済。クリックで開く。</summary>
ブランチB = feature/plicy-2019-2

WWAAudio関連, フレームカウント関連, その他雑多な機能追加を行うPhase

Phase2 のコードはすべてパスワードセーブの途中経過などが入っているので chery-pick で取り込む

- [x] f6c9ba6: スマートフォン環境で音が鳴らないという表記を削除、PC環境での分岐 #217 
- ~~9bf221c: 起動時のクリック必須表記をPC版以外で除外する処理をSE　OFFの場合の分岐でも修正~~ 前コミットで対応済み、取り込まなくてOK
- [x] 6da9d75: 方向転換だけする入力に対応（いわゆる振り向き）cf. bff9a52 #230 
- [x] 7e19570:  03da910: フレームカウントをwwaDataに追加, _~~useGameEnd導入~~ #235 
- ~~1b1cbc2: (ゲーム機のみ) BattleReportが正常に分岐されていない不具合を修正~~ 対応不要でした
- [x] 4c74c1c: WWAAudioのクラス化, フレームカウント計測・プレイ時間算出　#236 
- ~~cad9551: WWAAudioのクラスを default export~~ 上を動かすのに必要で手で直したので取り込まず
- ~~e31ed81: 音楽ファイルロードの修正~~ 修正済だった
- [x] a6d2e84: GoToWWA/BattleReport/GameEndの出し分けのリファクタ: Phase1でほぼ全部入っており、代入を1つ消すだけになった #240 
- [x] d28c323 15d5322 ed37ce5 842c181 : WebAudioでdisconnectで解放する処理を追加, AudioBufferのメモリ解放処理 #241 
- [x] ba5fd3d (部分cherry-pick)  `data-wwa-looking-around` 属性追加  無操作時に回る処理を入れるかどうか指定できる #245 
- ~~bff9a52  (部分cherry-pick) タッチ関係でスマホで動作しない不具合を修正~~ 既に入ってた
</details>

## Phase 3: パスワードセーブ圧縮  Phase 4と合わせて v3.5.0?  ~~#247~~ -> #270  
<details>
<summary>作業完了。クリックで開く。</summary>
### 初期のWWACompress関連: 1つのPRで対応 #248 
- [x] 75c8120: class WWACompress を wwa_psave に追加 背景・背景属性・物体・物体属性・メッセージ・システムメッセージの圧縮解凍に対応  (メッセージと属性は後のコミット 
afee9ff で除外されます)
- [x] 3706f6c: 代入ミスの修正
- [x] d090066: 連続した同一チップ配置の場合は圧縮処理する処理の追加
- [x] 68294eb: 正常にロードできないことがある不具合を修正
- [x] 4ae25e6: 0座標を書き換えた際にエラーが出る可能性があったため修正
- [x] 043dadf: コメント追加
- [x] ce44edd 当時の最新develop追従するマージコミット

### QuickSaveデータをIndexedDBに保存する: 1つのPRで対応 #249 
- [x]  5b0cbaa
  - 中断セーブのつなぎこみが wwa_main の各所に追加
  - 背景・物体の復元方法をCompress経由に変更
  - 関連メッセージが wwa_message に追加
  - EventEmitter風味なカスタムイベントリスナ wwaCustomEvent の追加
  - psaveにIndexedDB接続系のコード追加  
- [x] b4189f2
  - マップデータハッシュのセーブ時都度生成をやめる？
  - 中断時にQSボタンが凹んでしまう不具合を修正
  - アイテムが正常にロードされない不具合を修正
- [x] afee9ff
  - 背景属性・物体属性・メッセージをCompress対象から除外
  - Compress時にシャローコピー対策？で配列やオブジェクトを作り直す
- [x] fb7ab5e: 起動時に中断セーブの復元を実施するコードの場所を変更（復元データがplayerに反映されなかった）
- ( この間に Phase2 f6c9ba6 9bf221c )

### バイナリセーブ #252 
同一コミットに入ってる直接バイナリセーブ関係なさそうな修正系は「★」をつけます
- [x] a85f28f OS_TYPE.NINTENDO 時に UInt8Array を使ったバイナリセーブを実施 → compressUint8Array は 14f2023  で消える
- [x] dc0bdd8 Base64用の実験プログラムをWWACompressに追加 (呼び出しはされない) UInt8Arrayより高圧縮を目指す？　→  14f2023 で消える
- ( この間に Phase2 6da9d75 )
- [x] b651572 
  - WWACompress に `compressMapAllObject` 実装, 物体圧縮のコードから呼び出し
  - ~~★ セーブ禁止時にQuickSaveのDOMが生成される不具合修正 (Phase1)~~ 取り込み済
- [x] 96c2713
  - ~~★ 中断からの再開時にメッセージウィンドウのnull参照を回避するための MessageWindow, ScoreWindow を newする位置を変更, faceのクリア位置変更 (Phase1)~~ 取り込み済
  - Uint8Array型中断データ生成の処理を修正 (indexListCompress 処理が追加)
- [x] af5fe0b
  -  4saveで滑る（セーブウィンドウが出ている時に動ける？）不具合を修正
  - （複数QS・compress利用時において）存在しないデータを参照する不具合を修正
  - 再開後自動的にクイックセーブ枠に保存
- [x] 43799b8
   - ~~★ RequestAnimationFrameのベンダープレフィックス対応削除 (Phase1)~~
   - ★ wwaCustomEventで CustomEvent が利用できない判定を変更, 利用できない場合にイベントが正しく渡せていない不具合を修正 (Phase3)
   -  IE/Edge で IndexedDBの getAll がないためののエミュレーション
- [x] 4485251 正常にロードできないときに try-catch
- [x] 2486f68 ae8a58c セーブデータの受け渡しを文字列化されたJSON→オブジェクトに変更

### v3.2.0 調整系 #253 
- afaa721 3.2.0 マージ直前
- a1dc8c9 3.2.0 をマージ
- (この間に Phase2 7e19570 )
- 0fc129c 933f2c7 03da910 3.2.0 対応の各種調整
- (この間に Phase2 03da910 4c74c1c cad9551)
- 5df6884 package-lock.json の一部追加 
-  (この間に Phase2 e31ed81)

### Phase3に入れるべきだが、ディレクトリ整理後にコミットされたもの
ディレクトリ整理後にコミットされたが、ディレクトリ整理の影響を受けない差分

- [x] 36ed7fd: 不要なself除去　BGM読み込み前に再開した場合不具合がでるため、再開処理をBGM読み込み後に修正 #254 
</details>

## Phase 4 そして伝説へ... Phase 3と合わせてリリース ~~#247~~ -> #270
<details> 
<summary>クリックで開く。</summary>
- セーブ系ディレクトリ分割後に入れる必要がある対応
- ※Canvas軽量化対応

- [x] 787c98f: WWASaveをディレクトリに分離、オートセーブを実装 **バグあり 下記も取り込む**  #256 
  - [x] ced069e パスワードロードを使用しない場合に、データがありませんと表示される不具合を修正 (cherry-pickしてください) #256 
- [x] ba5fd3d: 
  - ~~★ `data-wwa-looking-around` 属性追加  無操作時に回る処理を入れるかどうか指定できる (Phase2)~~
  - オートセーブ間隔を定数で与える #256
- [x] bff9a52
  - IndexedDBのDB名・テーブル名を定数化, WWAConstsへ
  - ~~★タッチ関係でスマホで動作しない不具合を修正 Phase2~~
- ( 5f76d04 1c2b118 066e982 READMEの更新)
- [x] d5cbcc7 特定条件下で、クイックセーブ保存先がオートセーブ枠になってしまう不具合を修正
- ( d3dd46b マージコミット)
- [x] 14f2023: 
  - 利用しなくなった圧縮処理を除外
  - ランダム選択パーツの初期対策？  (FirstChangedMapUint8Table 追加)
- (この間 Phase1 baffea1  Phase2 1b1cbc2 Phase1 19deec9 385dd53 Phase4(先行cherry-pick) ced069e, Phase2 a6d2e84)
- [x] 7346857
  - クイックセーブの際に圧縮をしない処理の追加
  - Passwordを使えない環境ではQuick Loadの初期表示を空白化
- [x] beadf69
  - QUICK SAVEできない際は非表示にするように変更
  - ボタンテキストを WWAButtonTexts として wwa_data の定数値とする
- [x] 661b52d: 最新クイックセーブの日付を黄色で表示
- (この間 Phase 3 36ed7fd )
- [x] 01f4981
   - ※ canvas1枚化 サブのキャンバスに描画していたものはalpha:trueのcontextで描画 
   - passwordで正常に保存されていないのを修正。オートセーブの軽量化
- [x] c0070ec 注) LF -> CRLFになってそう こっち見たほうがいい→ https://github.com/WWAWing/WWAWing/pull/100/commits/c0070ec8440ee128a6c27a0055beae5b61a5bba2?diff=split&w=1
  - ※ MapObjectとEffetsのキャンバスキャッシュ化  **バグあり 後続の de1a9b0とセット**
  - ※ クリックの文章表記を端末により変更
  - セーブ処理のバグ修正
- (この間 Phase2 d28c323, 15d5322 ed37ce5 842c181)
- [x] de1a9b0 ※戦闘中の描画不具合回避 上記とセットでが望ましい
- [x] ca594f0 b14135e ※EDGEでキャンバスが消えないことがある不具合を修正, 
灰色にならない塗りつぶしを修正 ※ 01f4981 のalpha化とセットでphase2
- [x] debf736 日本語の日時に対応
</details>

**Comment by matsuyuki-a** [comment]
memo: Phase2のdevelopマージ→Phase3,4作業→リリースかなぁ

**Comment by matsuyuki-a** [comment]
以降は 最新まで追従する #270  のPRで扱うものとし、このIssueはCloseします。
